version: "3"
services:
    web:
        build: .
        ports:
            - "7777:5000"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "iH@jJc5uHa1j"
            ACCEPT_EULA: "Y"
            ASPNETCORE_ENVIRONMENT: "Docker"